apiVersion: v1
kind: Service
metadata:
  namespace: three-tier
  name: mongodb-svc
  labels:
    app: mongodb
spec:
  clusterIP: None  # This makes it headless
  ports:
  - port: 27017
    name: mongodb
  selector:
    app: mongodb  