apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: three-tier
  name: mongodb
spec:
  serviceName: "mongodb"  # Must match headless service name
  replicas: 1  # For production, consider 3 replicas with replica sets
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.6
        command:
          - "mongod"
          - "--bind_ip_all"
          - "--replSet"
          - "rs0"  # Enable replication for multi-pod setup
          - "--keyFile"
          - "/etc/mongo-keyfile/keyfile"
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
          - name: mongo-keyfile
            mountPath: /etc/mongo-keyfile
            readOnly: true
  volumeClaimTemplates:  # Each pod gets its own PVC
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-storage"  # Or your storage class
      resources:
        requests:
          storage: 1Gi


          