apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: three-tier
type: Opaque
stringData:
  MONGO_CONNECTION_STRING: "MONGO_CONNECTION_STRING"
  JWT_SECRET_KEY: "<JWT_SECRET_KEY>"
  CLOUDINARY_API_SECRET: "<CLOUDINARY_API_SECRET>"
  STRIPE_API_KEY: "<STRIPE_API_KEY>"
